import { Box, Title } from '@mantine/core';
import Head from 'next/head';
import { NextPage } from 'next/types';
import AppLayout from '../modules/layout/AppLayout';
import CheckoutList from '../modules/product/components/CheckoutList';
import useCart from '../modules/user/hooks/useCart';
import useMe from '../store/useMe';

const Checkout: NextPage = () => {
  // get all products from user cart
  // fallback to localstorage
  const { user } = useMe();
  const { isLoading, data } = useCart(user!.id);

  return (
    <Box>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <Title sx={{ marginBottom: 20 }}>Checkout</Title>
        {isLoading ? undefined : <CheckoutList data={data!.products} />}
      </AppLayout>
    </Box>
  );
};

export default Checkout;
