import { Box, Title } from '@mantine/core';
import Head from 'next/head';
import { NextPage } from 'next/types';
import { useQuery } from 'react-query';
import axios from '../lib/axios';
import AppLayout from '../modules/layout/AppLayout';
import CheckoutList from '../modules/product/components/CheckoutList';

const Checkout: NextPage = () => {
  // get all products from user cart
  // fallback to localstorage
  // ! Hardcoded user id
  const { isLoading, data } = useQuery('user/5/cart', () =>
    axios.get('/user/5/cart').then((response) => response.data)
  );

  return (
    <Box>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <Title sx={{ marginBottom: 20 }}>Checkout</Title>
        {isLoading ? undefined : <CheckoutList data={data.products} />}
      </AppLayout>
    </Box>
  );
};

export default Checkout;
